services:
  db:
    image: postgres:16.9-alpine
    env_file: .env
    volumes:
      - db:/var/lib/postgresql/data
      - ./queries/create_db.sql:/docker-entrypoint-initdb.d/create_database.sql
    ports:
      - 5432:5432
    networks:
      - db

networks:
  db:
    driver: bridge

volumes:
  db:


